### ISSUE TITLE
Aiming at the ground when detect an enemy

### ISSUE THREAD

**Issue by bimaxc** [ofeksadlo/CSGO-Aimbot-CNN#1]
Video : [https://streamable.com/uu8ama](url)

my game settings

fullscreen windowed
1920x1080
using pygame.HWSURFACE

**Comment by ofeksadlo** [comment]
As instructed in the readme your raw_input needs to be disabled.
And keep in mind the entire dataset is collected as for now on dust2.
In the future the dataset will include more maps.
