### ISSUE TITLE
Custom object detector 

### ISSUE THREAD

**Issue by sneakybeaky18** [ofeksadlo/CSGO-Aimbot-CNN#12]
Hello! Can you please explain how do you build your custom neural network with object detection? I want to made it by myself, but all i found in internet its guides with TF object detection api. Can you pless tell some guides/resources where i can find some info about how to make it by myself, like in jupyter notebook, you know like ordinary models a.k.a catboost / keras models / unet and etc... without this tf object detection api. i want to build custom model by myself and change the layers, inputs and other stuff in educational purposes  and your neural network build without this apis.. i hope you you give some information. thank you in advance

**Comment by ofeksadlo** [comment]
This will help you get started:
[https://www.youtube.com/playlist?list=PLMoSUbG1Q_r8nz4C5Yvd17KaXy8p0ufPH](https://www.youtube.com/playlist?list=PLMoSUbG1Q_r8nz4C5Yvd17KaXy8p0ufPH)

**Comment by KingMisha** [comment]
Would this help in making it capable to work on other games?

**Comment by sneakybeaky18** [comment]
> This will help you get started:
> https://www.youtube.com/playlist?list=PLMoSUbG1Q_r8nz4C5Yvd17KaXy8p0ufPH

thank you so much 😊
