### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Daemon7895** [ofeksadlo/CSGO-Aimbot-CNN#14]
Hello,
I'm an IT Student, and I'm actually really interesting in all machine learning things, I found your repository and I was so hyped so I wanted to try it out but I got 2 errors that I cannot resolve. Can you help me pls ?

```
> Traceback (most recent call last):
>   File "C:\Users\Daymonz\Documents\CSGO-Aimbot-CNN-main\assets\aimbotOnly.py", line 191, in <module>
>     outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
>   File "C:\Users\Daymonz\Documents\CSGO-Aimbot-CNN-main\assets\aimbotOnly.py", line 191, in <listcomp>
>     outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
> IndexError: invalid index to scalar variable.
```

**Comment by ofeksadlo** [comment]
have you installed all the [dependencies](https://github.com/ofeksadlo/CSGO-Aimbot-CNN/blob/main/requirements.txt)?
And have you followed all the [instructions](https://github.com/ofeksadlo/CSGO-Aimbot-CNN#how-to-make-it-work)?
If both are a "Yes".
Then try to use [Python 3.7.7](https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe)
That's the environment I used.

**Comment by Daemon7895** [comment]
I did yes
I installed python 3.7.7, installed all depedencies, I got all the correct
versions.

**Comment by Daemon7895** [comment]
I tested it on another pc and I got the same error, perhaps it's the depedencies versions

**Comment by Daemon7895** [comment]
You didn't mention that in the requirements.txt

**Comment by Daemon7895** [comment]
Ok, so I made it work. 
The actual depedencies versions aren't compatible with your code
So I just downgraded them :
- pip install pywin32==228
- pip install opencv-contrib-python==4.4.0.42
- pip install pynput==1.7.1
- pip install numpy==1.16.0
- pip install PyAutoGUI==0.9.50
- pip install pygame==2.0.0.dev10
- pip install mss==6.0.0
- pip install keyboard==0.13.5
- pip install mouse==0.7.1
- pip install tensorflow-directml==1.15.3.dev200626

By the way, is there a way to train the AI, cause it's very hard to detect a terrorist

**Comment by ofeksadlo** [comment]
> Ok, so I made it work. The actual depedencies versions aren't compatible with your code So I just downgraded them :
> 
> * pip install pywin32==228
> * pip install opencv-contrib-python==4.4.0.42
> * pip install pynput==1.7.1
> * pip install numpy==1.16.0
> * pip install PyAutoGUI==0.9.50
> * pip install pygame==2.0.0.dev10
> * pip install mss==6.0.0
> * pip install keyboard==0.13.5
> * pip install mouse==0.7.1
> * pip install tensorflow-directml==1.15.3.dev200626
> 
> By the way, is there a way to train the AI, cause it's very hard to detect a terrorist

Great!
I will update the requirements.

And for your question It doesn't suprise me it doesn't work well.
The dataset I've created doesn't include the new ct / t models.
But Yes you can train the model yourself
Here is the dataset I've collected: [https://drive.google.com/file/d/1MEYhHxJc46gEap0y558SmhygIzCfdXJa](https://drive.google.com/file/d/1MEYhHxJc46gEap0y558SmhygIzCfdXJa)
You can expand it.

**Comment by Daemon7895** [comment]
OK thank you, I will try to train the model to detect the new ct and t heads

**Comment by Daemon7895** [comment]
By the way, I found a great bank of datas for csgo lol 3d.cs.money, here you can visualise all agents, weapons etc... on differents backgrounds and distances, luminosity, and rotations

**Comment by Daemon7895** [comment]
Just a last question, how to train the AI with your code ?. Cause I got a lot of datas, but I'm a "beginner" in this domain, so if you could enlighten me.

**Comment by ofeksadlo** [comment]
> Just a last question, how to train the AI with your code ?. Cause I got a lot of datas, but I'm a "beginner" in this domain, so if you could enlighten me.

It's a yolov4-tiny model I trained and inferced.
Just google "how to train yolov4 model"
You'll find a lot of tutorials.
