### ISSUE TITLE
 does it only work in csgo?

### ISSUE THREAD

**Issue by Allmight0000** [ofeksadlo/CSGO-Aimbot-CNN#26]
does it only work in csgo?

**Comment by Allmight0000** [comment]
I can't install all the requirements     
ERROR: Could not find a version that satisfies the requirement pygame==2.0.0.dev10 (from versions: 1.9.2rc1, 1.9.2, 1.9.3, 1.9.4.dev0, 1.9.4rc1, 1.9.4, 1.9.5rc1, 1.9.5rc2, 1.9.5, 1.9.6rc1, 1.9.6rc2, 1.9.6, 2.0.0.dev12, 2.0.0.dev14, 2.0.0.dev16, 2.0.0.dev18, 2.0.0.dev20, 2.0.0.dev22, 2.0.0.dev24, 2.0.0, 2.0.1.dev1, 2.0.1, 2.0.2.dev4, 2.0.2, 2.0.3.dev4, 2.0.3.dev6, 2.0.3, 2.1.0.dev2, 2.1.0, 2.1.1.dev2, 2.1.1.dev4, 2.1.1, 2.1.2, 2.1.3.dev6, 2.1.3.dev8, 2.1.3, 2.2.0.dev2, 2.2.0, 2.3.0.dev2)
ERROR: No matching distribution found for pygame==2.0.0.dev10

**Comment by ofeksadlo** [comment]
You probabbly have a too advenced version of python
Try using Python 3.7.7

Just a heads up this is not going to work very well. The model
was trained on player skins from 3 years ago.
So this is not an easy to use cheat it's an educational project.

**Comment by ofeksadlo** [comment]
You probabbly have a too advanced version of python
Try using Python 3.7.7

Just a heads up this is not going to work very well. The model
was trained on player skins from 3 years ago.
So this is not an easy to use cheat it's an educational project.
