### ISSUE TITLE
Can this project work with TPUs or VPUs?

### ISSUE THREAD

**Issue by eren-erver** [ofeksadlo/CSGO-Aimbot-CNN#6]
I am planning to buy a TPU/VPU accelerator like Google Coral M.2 TPU Accelerator , Google Coral USB TPU Accelerator or maybe intel neural compute stick 2(VPU). I was just curious about it. Would this project work with TPU/VPU accelerators ? The only problem I know is that Google Coral Accelerators support TF Lite so I guess I should convert the model to tf lite but that would decrease the accuracy. On the other hand , intel neural compute stick 2 supports tensorflow.

**Comment by ofeksadlo** [comment]
I'm not that familiar with TPU/VPU accelerators. 
But you should manage to make it work I easily found this repository: [Edge TPU - Tiny YOLO v3
](https://github.com/guichristmann/edge-tpu-tiny-yolo) that should be useful.
Although I can almost guarantee the accuracy will go to hell with the conversion.
From my own experience of trying to utilize DirectML for GPU acceleration.
The converted models accuracy was so bad
I'm still looking for another method to improve results.

**Comment by eren-erver** [comment]
Ok thank you I have a problem with your code but I will create a new issue for that to make it easier to find.
